apiVersion: v1
kind: Pod
metadata:
  name: mysql-test-app
  namespace: vault-rotation-demo
spec:
  containers:
  - name: vault-rotation-app
    image: vaultrotation:0.0.1-SNAPSHOT
    env:
    - name: SPRING_DATASOURCE_URL
      value: "jdbc:mysql://host.minikube.internal:3306/payments?useSSL=false&allowPublicKeyRetrieval=true"
    - name: SPRING_DATASOURCE_USERNAME
      value: "root"
    - name: SPRING_DATASOURCE_PASSWORD
      value: "rootpassword"
    - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
      value: "com.mysql.cj.jdbc.Driver"
    - name: VAULT_ADDR
      value: "http://vault.vault.svc.cluster.local:8200"
    - name: VAULT_TOKEN
      valueFrom:
        secretKeyRef:
          name: vault-token
          key: token 