apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  namespace: vault-rotation-demo
spec:
  containers:
  - name: mysql-client
    image: mysql:8
    command:
    - sleep
    - "3600"
    env:
    - name: MYSQL_PWD
      value: "root" 