apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-rotation-config
  namespace: vault-rotation-demo
data:
  application.properties: |
    # Configurações do servidor
    server.port=8080
    
    # Configurações de JPA
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
    spring.jpa.open-in-view=false
    
    # Driver JDBC
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    
    # Configuração do banco de dados 
    spring.datasource.url=jdbc:mysql://host.minikube.internal:3306/payments?useSSL=false&allowPublicKeyRetrieval=true
    
    # Configurações para habilitar o Vault
    spring.cloud.vault.enabled=true
    spring.cloud.bootstrap.enabled=true
    spring.config.import=vault://
    
    # Configurações de TTL para rotação
    spring.cloud.vault.config.lifecycle.enabled=true
    spring.cloud.vault.config.lifecycle.min-renewal=10s
    spring.cloud.vault.config.lifecycle.expiry-threshold=1m
    
    # Configurações de log
    logging.level.org.springframework.cloud.vault=DEBUG
    logging.level.com.example.vaultrotation=DEBUG
    
    # Configuração para mostrar SQL
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.format_sql=true
    
    # Incluir endpoints para gerenciamento
    management.endpoints.web.exposure.include=health,info,refresh

  bootstrap.properties: |
    # Nome da aplicação (usado pelo Vault para buscar segredos)
    spring.application.name=vault-rotation
    
    # Configuração do Vault
    spring.cloud.vault.uri=${VAULT_ADDR:http://vault.vault.svc.cluster.local:8200}
    spring.cloud.vault.token=${VAULT_TOKEN}
    spring.cloud.vault.scheme=http
    spring.cloud.vault.fail-fast=false
    spring.cloud.vault.enabled=true
    
    # Configuração do ciclo de vida dos segredos
    spring.cloud.vault.config.lifecycle.enabled=true
    spring.cloud.vault.config.lifecycle.min-renewal=10s
    spring.cloud.vault.config.lifecycle.expiry-threshold=1m
    
    # Configuração do banco de dados secretos
    spring.cloud.vault.database.enabled=true
    spring.cloud.vault.database.role=payments-app
    spring.cloud.vault.database.backend=database
    
    # Configuração do backend de key-value para secrets estáticas
    spring.cloud.vault.kv.enabled=true
    spring.cloud.vault.kv.backend=kv
    spring.cloud.vault.kv.default-context=application
    spring.cloud.vault.kv.application-name=vault-rotation
    
    # Importar configuração do Vault
    spring.config.import=vault://
    
    # URL do banco de dados
    spring.datasource.url=jdbc:mysql://${DATABASE_URL:host.minikube.internal:3306/payments}?useSSL=false&allowPublicKeyRetrieval=true
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    
    # Expor endpoint de refresh para atualizações manuais se necessário
    management.endpoints.web.exposure.include=refresh,health,info 