apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-rotation-app
  namespace: vault-rotation-demo
  labels:
    app: vault-rotation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-rotation-app
  template:
    metadata:
      labels:
        app: vault-rotation-app
      annotations:
        timestamp: "${TIMESTAMP}"
    spec:
      containers:
      - name: vault-rotation-app
        image: vault-rotation-app:snapshot
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: VAULT_ADDR
          value: "http://vault:8200"
        - name: VAULT_TOKEN
          value: "root"
        - name: MYSQL_ADMIN_HOST
          value: "host.minikube.internal"
        - name: MYSQL_ADMIN_PORT
          value: "3306"
        - name: MYSQL_ADMIN_USERNAME
          value: "root"
        - name: MYSQL_ADMIN_PASSWORD
          value: "rootpassword"
        - name: DATABASE_URL
          value: "host.minikube.internal:3306/payments"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://host.minikube.internal:3306/payments?useSSL=false&allowPublicKeyRetrieval=true"
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: "com.mysql.cj.jdbc.Driver"
        - name: LOGGING_LEVEL_COM_EXAMPLE_VAULTROTATION
          value: "DEBUG"
        - name: SPRING_CLOUD_VAULT_URI
          value: "http://vault.vault.svc.cluster.local:8200"
        - name: SPRING_CLOUD_VAULT_TOKEN
          value: "root"
        - name: SPRING_CLOUD_VAULT_DATABASE_ROLE
          value: "payments-app"
        - name: SPRING_CLOUD_VAULT_DATABASE_BACKEND
          value: "database"
        - name: SPRING_CLOUD_VAULT_ENABLED
          value: "true"
        - name: SPRING_CONFIG_IMPORT
          value: "vault://"
        - name: SPRING_CLOUD_VAULT_FAIL_FAST
          value: "false"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
      volumes:
      - name: config-volume
        configMap:
          name: vault-rotation-config 