apiVersion: v1
kind: Service
metadata:
  name: vault-rotation-app
  namespace: vault-rotation-demo
spec:
  selector:
    app: vault-rotation-app
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP 